// بيانات الهيكل الكامل — الأجزاء والعناصر
// tag: "new" = إضافة مقترحة | "moved" = نُقل | "merged" = دُمج
const PARTS = [
{ title: "الجزء الأول: مقدمة المشروع (Project Foundation)", items: [
  "مقدمة المشروع (Project Overview)",
  "الرؤية والرسالة (Vision & Mission)",
  "أهداف النظام (System Objectives)",
  "نطاق المشروع (Project Scope)",
  "حدود النظام (System Boundaries)",
  "الفرضيات والقيود (Assumptions & Constraints)",
  "المصطلحات والاختصارات (Glossary & Acronyms)",
  "المراجع والمعايير (References & Standards)",
]},
{ title: "الجزء الثاني: تحليل الأعمال (Business Analysis)", items: [
  "أصحاب المصلحة (Stakeholders)",
  "احتياجات الأعمال (Business Requirements)",
  "الأهداف الإستراتيجية (Strategic Objectives)",
  "مؤشرات الأداء الرئيسية (KPIs)",
  "حالات الاستخدام (Use Cases)",
  "سيناريوهات الأعمال (Business Scenarios)",
  "Business Rules",
  "Validation Rules",
  "Decision Matrix",
  "Business Process Modeling (BPMN)",
  { text: "تحليل التكلفة والجدوى (Cost-Benefit Analysis / ROI)", tag: "new" },
  { text: "سجل المخاطر المبدئي (Initial Risk Register)", tag: "new", note: "يُفتح هنا ويُحدَّث باستمرار طوال الوثيقة" },
]},
{ title: "الجزء الثالث: التحليل الوظيفي (Functional Analysis)", items: [
  "الوحدات الرئيسية للنظام",
  "إدارة المستخدمين",
  "إدارة الصلاحيات",
  "إدارة المدارس",
  "إدارة الفروع",
  "إدارة العام الدراسي",
  "إدارة الصفوف",
  "إدارة الشعب",
  "إدارة المواد",
  "إدارة المعلمين",
  { text: "القبول والتسجيل (Admissions & Enrollment)", tag: "new", note: "التقديم، المفاضلة، القبول المشروط، النقل بين المدارس" },
  "إدارة الطلاب",
  "إدارة أولياء الأمور",
  { text: "بوابة الطالب وولي الأمر (Student/Parent Portal)", tag: "new" },
  { text: "الجدول الدراسي والجدولة (Timetabling & Scheduling)", tag: "new", note: "تعارض المعلمين، القاعات، والحصص" },
  "إدارة الحضور والانصراف",
  { text: "السلوك والانضباط (Behavior & Discipline)", tag: "new" },
  "إدارة الاختبارات",
  "إدارة الدرجات",
  { text: "الشهادات والوثائق الرسمية (Certificates & Transcripts)", tag: "new" },
  { text: "إدارة الرسوم، الإدارة المالية، والمحاسبة", tag: "merged", note: "دُمجت مع توضيح الحدود الوظيفية بين الثلاثة" },
  "المخزون",
  "الموارد البشرية",
  "الأصول",
  "المكتبة",
  "النقل المدرسي",
  "السكن",
  "الصحة المدرسية",
  { text: "الأنشطة اللامنهجية (Extracurricular Activities)", tag: "new" },
  "الإشعارات",
  "الرسائل",
  "التقارير",
  "لوحة التحكم",
]},
{ title: "الجزء الرابع: المتطلبات غير الوظيفية (Non-Functional Requirements)", items: [
  "الأداء (Performance)",
  "الأمان (Security)",
  "الاعتمادية (Reliability)",
  "القابلية للتوسع (Scalability)",
  "القابلية للصيانة (Maintainability)",
  "التوافر (Availability)",
  "سهولة الاستخدام (Usability)",
  "قابلية الاختبار (Testability)",
  "الامتثال (Compliance)",
  "النسخ الاحتياطي (Backup)",
  "استعادة الكوارث (Disaster Recovery)",
  { text: "Localization / Time Zones / Currency", tag: "moved", note: "قرار تصميم مبكر يؤثر على البنية، نُقل من إدارة النظام" },
]},
{ title: "الجزء الخامس: هندسة النظام (System Architecture)", items: [
  "الرؤية المعمارية","Enterprise Architecture","Architectural Principles",
  "Clean Architecture","Layered Architecture","Modular Architecture",
  "Microservices Readiness","Domain Driven Design (DDD)","Bounded Contexts",
  "Domain Model","Component Architecture","Deployment Architecture",
  "Infrastructure Architecture","Network Architecture",
]},
{ title: "الجزء السادس: سير العمليات (Workflow Architecture)", items: [
  "Workflow Overview","Workflow Engine","Approval Workflow","State Machine",
  "Event Driven Architecture","Event Catalog","Background Jobs","Scheduler",
  "Notification Workflow",
]},
{ title: "الجزء السابع: تصميم قاعدة البيانات (Database Architecture)", items: [
  "Database Overview","ERD","Database Schema","Master Tables",
  "Transaction Tables","Reference Tables","Constraints","Indexing Strategy",
  "Partition Strategy","Read Replica Strategy","Data Archiving","Database Security",
]},
{ title: "الجزء الثامن: تصميم API", items: [
  "API Architecture","REST API Standards","API Authentication","Authorization",
  "API Versioning","Request Validation","Response Standards","Error Handling",
  "Rate Limiting","Webhooks","API Documentation",
]},
{ title: "الجزء التاسع: التكامل (Integration)", items: [
  "Integration Architecture","Payment Gateway","SMS Gateway","Email Services",
  "WhatsApp Integration","Government Services","Identity Providers",
  "Microsoft 365","Google Workspace","LMS Integration","Third-party APIs",
]},
{ title: "الجزء العاشر: الأمن السيبراني (Security Architecture)", items: [
  "Security Overview","Identity Management","RBAC","ABAC","JWT","OAuth2",
  "OpenID Connect","Encryption","Audit Logs","Security Logs","OWASP",
  "ISO 27001","NCA ECC","PDPL Compliance",
]},
{ title: "الجزء الحادي عشر: الذكاء الاصطناعي (AI Architecture)", items: [
  "AI Strategy","AI Services","Prompt Engineering","RAG Architecture",
  "Vector Database","Knowledge Base","AI Gateway","AI Security","AI Use Cases",
]},
{ title: "الجزء الثاني عشر: التقارير والتحليلات (Reporting & Analytics)", items: [
  "Reporting Architecture","Dashboard","BI Reports","KPI Reports",
  "Data Warehouse","ETL","OLAP","Power BI Integration",
]},
{ title: "الجزء الثالث عشر: الأداء (Performance)", items: [
  "Caching Strategy","Redis","Search Engine","Elasticsearch",
  "Performance Optimization","Horizontal Scaling","Vertical Scaling","Load Balancing",
]},
{ title: "الجزء الرابع عشر: المراقبة والتشغيل (Operations)", items: [
  "Logging Strategy","Monitoring","Observability","Metrics",
  "Distributed Tracing","Alerting","Health Checks",
]},
{ title: "الجزء الخامس عشر: DevOps", items: [
  "Source Control","Git Strategy","CI/CD","Docker","Kubernetes","Helm",
  "Infrastructure as Code","Terraform","Release Management",
]},
{ title: "الجزء السادس عشر: جودة البرمجيات (Software Quality)", items: [
  "Coding Standards","Naming Convention","Repository Pattern","Unit of Work",
  "CQRS","Design Patterns","Unit Testing","Integration Testing",
  "Performance Testing","Security Testing",
]},
{ title: "الجزء السابع عشر: إدارة النظام (Administration)", items: [
  "Configuration Center","Feature Flags","Multi-Tenant Management",
  { text: "Localization", note: "التطبيق التشغيلي فقط؛ القرار المعماري انتقل للجزء الرابع" },
  "Time Zones","Currency Management","Academic Settings","Global Settings",
]},
{ title: "الجزء الثامن عشر: التشغيل والاستمرارية (Business Continuity)", items: [
  "Backup Strategy","Disaster Recovery Plan","SLA","SLO",
  "Incident Management","Change Management",
  { text: "خطة ترحيل البيانات (Data Migration Plan)", tag: "new" },
]},
{ title: "الجزء التاسع عشر: التوثيق الهندسي (Technical Documentation)", items: [
  "UML Diagrams","Sequence Diagrams","Class Diagrams","Activity Diagrams",
  "Component Diagrams","Deployment Diagrams","ADR (Architecture Decision Records)",
  "Software Design Document (SDD)",
]},
{ title: "الجزء العشرون: التنفيذ (Implementation)", items: [
  "خطة التنفيذ","مراحل التطوير","الجدول الزمني",
  "إدارة المخاطر (تحديث سجل المخاطر المفتوح في الجزء الثاني)",
  "خطة الاختبارات","خطة الإطلاق","خطة التدريب","خطة الدعم والصيانة",
  "خارطة الطريق المستقبلية (Roadmap)",
]},
];
